ERROR - 2022-01-01 05:34:34 --> Error connecting to the database: No connection could be made because the target machine actively refused it.

CRITICAL - 2022-01-01 05:34:34 --> Unable to connect to the database.
Main connection [MySQLi]: No connection could be made because the target machine actively refused it.

#0 D:\Leptop\web\htdocs\Web1\login\system\Database\BaseConnection.php(577): CodeIgniter\Database\BaseConnection->initialize()
#1 D:\Leptop\web\htdocs\Web1\login\system\Database\BaseBuilder.php(1443): CodeIgniter\Database\BaseConnection->query('SELECT *\nFROM `...', Array, false)
#2 D:\Leptop\web\htdocs\Web1\login\system\Model.php(210): CodeIgniter\Database\BaseBuilder->get()
#3 D:\Leptop\web\htdocs\Web1\login\system\BaseModel.php(622): CodeIgniter\Model->doFirst()
#4 D:\Leptop\web\htdocs\Web1\login\vendor\myth\auth\src\Authentication\LocalAuthenticator.php(156): CodeIgniter\BaseModel->first()
#5 D:\Leptop\web\htdocs\Web1\login\vendor\myth\auth\src\Authentication\LocalAuthenticator.php(20): Myth\Auth\Authentication\LocalAuthenticator->validate(Array, true)
#6 D:\Leptop\web\htdocs\Web1\login\vendor\myth\auth\src\Controllers\AuthController.php(88): Myth\Auth\Authentication\LocalAuthenticator->attempt(Array, false)
#7 D:\Leptop\web\htdocs\Web1\login\system\CodeIgniter.php(824): Myth\Auth\Controllers\AuthController->attemptLogin()
#8 D:\Leptop\web\htdocs\Web1\login\system\CodeIgniter.php(410): CodeIgniter\CodeIgniter->runController(Object(Myth\Auth\Controllers\AuthController))
#9 D:\Leptop\web\htdocs\Web1\login\system\CodeIgniter.php(318): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#10 D:\Leptop\web\htdocs\Web1\login\public\index.php(37): CodeIgniter\CodeIgniter->run()
#11 C:\Users\Robin\AppData\Roaming\Composer\vendor\cretueusebiu\valet-windows\server.php(241): require('D:\\Leptop\\web\\h...')
#12 {main}
